require('dotenv').config();
const bcrypt = require('bcryptjs');
const {
  sequelize, User, KeywordResearch, ContentGeneration, MetaTag, SEOAudit,
  BacklinkAnalysis, ContentOptimizer, SERPAnalysis, CompetitorAnalysis,
  TitleGenerator, BlogPost, ProductDescription, FAQGenerator,
  SchemaMarkup, ContentCalendar, ReadabilityAnalysis
} = require('./models');

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('Connected to database.');
    await sequelize.sync({ force: true });
    console.log('Tables created.');

    // Create demo user
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash('password123', salt);
    const user = await User.create({
      email: 'demo@seocontent.ai',
      password: hashedPassword,
      name: 'Demo User',
      role: 'admin'
    });
    const userId = user.id;
    console.log('Demo user created: demo@seocontent.ai / password123');

    // Seed Keyword Research (15 items)
    const keywords = [
      { keyword: 'best SEO tools 2024', searchVolume: 45000, difficulty: 'hard', cpc: 8.50, intent: 'commercial', relatedKeywords: 'SEO software, SEO platforms, top SEO tools', status: 'active' },
      { keyword: 'how to improve website ranking', searchVolume: 32000, difficulty: 'medium', cpc: 5.20, intent: 'informational', relatedKeywords: 'improve SEO, boost rankings, website optimization', status: 'active' },
      { keyword: 'content marketing strategy', searchVolume: 28000, difficulty: 'hard', cpc: 12.30, intent: 'informational', relatedKeywords: 'content strategy, digital marketing, content plan', status: 'active' },
      { keyword: 'keyword research tools free', searchVolume: 22000, difficulty: 'medium', cpc: 4.80, intent: 'transactional', relatedKeywords: 'free SEO tools, keyword planner, keyword finder', status: 'active' },
      { keyword: 'on-page SEO checklist', searchVolume: 18000, difficulty: 'easy', cpc: 3.50, intent: 'informational', relatedKeywords: 'SEO checklist, on-page optimization, SEO guide', status: 'active' },
      { keyword: 'backlink building strategies', searchVolume: 15000, difficulty: 'hard', cpc: 9.70, intent: 'informational', relatedKeywords: 'link building, backlinks, outreach strategy', status: 'active' },
      { keyword: 'local SEO optimization', searchVolume: 25000, difficulty: 'medium', cpc: 7.40, intent: 'informational', relatedKeywords: 'local search, Google My Business, local rankings', status: 'active' },
      { keyword: 'technical SEO audit', searchVolume: 12000, difficulty: 'hard', cpc: 11.20, intent: 'transactional', relatedKeywords: 'site audit, technical SEO, website analysis', status: 'active' },
      { keyword: 'blog post writing tips', searchVolume: 35000, difficulty: 'easy', cpc: 2.80, intent: 'informational', relatedKeywords: 'blogging tips, writing guide, content creation', status: 'active' },
      { keyword: 'e-commerce SEO guide', searchVolume: 20000, difficulty: 'hard', cpc: 14.50, intent: 'informational', relatedKeywords: 'online store SEO, product page SEO, shop optimization', status: 'active' },
      { keyword: 'meta description best practices', searchVolume: 9500, difficulty: 'easy', cpc: 2.30, intent: 'informational', relatedKeywords: 'meta tags, SEO meta, description optimization', status: 'active' },
      { keyword: 'voice search optimization', searchVolume: 16000, difficulty: 'medium', cpc: 6.80, intent: 'informational', relatedKeywords: 'voice SEO, smart speaker, conversational search', status: 'active' },
      { keyword: 'mobile SEO best practices', searchVolume: 21000, difficulty: 'medium', cpc: 5.90, intent: 'informational', relatedKeywords: 'mobile optimization, responsive design, mobile-first', status: 'active' },
      { keyword: 'SEO competitor analysis tools', searchVolume: 14000, difficulty: 'hard', cpc: 10.40, intent: 'commercial', relatedKeywords: 'competitor research, SEO spy tools, competition analysis', status: 'active' },
      { keyword: 'Google algorithm updates 2024', searchVolume: 42000, difficulty: 'medium', cpc: 4.10, intent: 'informational', relatedKeywords: 'Google update, algorithm change, SERP changes', status: 'active' },
    ];
    await KeywordResearch.bulkCreate(keywords.map(k => ({ ...k, userId })));
    console.log('Seeded 15 keyword research items.');

    // Seed Content Generation (15 items)
    const contents = [
      { title: 'Ultimate Guide to SEO in 2024', contentType: 'blog_post', targetKeyword: 'SEO guide 2024', content: 'Comprehensive guide covering all aspects of modern SEO including technical, on-page, and off-page strategies...', wordCount: 2500, seoScore: 92, status: 'published' },
      { title: 'How to Create Engaging Blog Content', contentType: 'blog_post', targetKeyword: 'engaging blog content', content: 'Learn the secrets to creating blog posts that captivate your audience and drive organic traffic...', wordCount: 1800, seoScore: 87, status: 'published' },
      { title: 'E-commerce Product Page Optimization', contentType: 'guide', targetKeyword: 'product page SEO', content: 'Step-by-step guide to optimizing your e-commerce product pages for maximum search visibility...', wordCount: 2200, seoScore: 90, status: 'draft' },
      { title: '10 Link Building Strategies That Work', contentType: 'listicle', targetKeyword: 'link building strategies', content: 'Proven link building techniques that will help you earn high-quality backlinks and boost your domain authority...', wordCount: 3000, seoScore: 95, status: 'published' },
      { title: 'Understanding Search Intent for SEO', contentType: 'blog_post', targetKeyword: 'search intent SEO', content: 'Master the concept of search intent to create content that matches what users are really looking for...', wordCount: 1500, seoScore: 85, status: 'published' },
      { title: 'Local SEO: Complete Beginner Guide', contentType: 'guide', targetKeyword: 'local SEO guide', content: 'Everything you need to know about local SEO to get your business found in local search results...', wordCount: 2800, seoScore: 88, status: 'draft' },
      { title: 'Content Clusters and Topic Authority', contentType: 'blog_post', targetKeyword: 'content clusters', content: 'How to build content clusters that establish topical authority and improve your overall search rankings...', wordCount: 2000, seoScore: 91, status: 'published' },
      { title: 'Technical SEO Fundamentals', contentType: 'guide', targetKeyword: 'technical SEO', content: 'Core technical SEO concepts including crawlability, indexability, site speed, and structured data...', wordCount: 3200, seoScore: 93, status: 'published' },
      { title: 'Social Media and SEO Connection', contentType: 'blog_post', targetKeyword: 'social media SEO', content: 'Exploring the relationship between social media signals and search engine rankings...', wordCount: 1600, seoScore: 82, status: 'draft' },
      { title: 'Image SEO Optimization Guide', contentType: 'guide', targetKeyword: 'image SEO', content: 'Complete guide to optimizing images for search engines including alt text, file names, and compression...', wordCount: 1900, seoScore: 86, status: 'published' },
      { title: 'SEO for SaaS Companies', contentType: 'blog_post', targetKeyword: 'SaaS SEO', content: 'Tailored SEO strategies specifically designed for SaaS businesses to drive organic signups...', wordCount: 2400, seoScore: 89, status: 'published' },
      { title: 'Core Web Vitals Optimization', contentType: 'guide', targetKeyword: 'core web vitals', content: 'How to measure and improve your Core Web Vitals scores for better search rankings...', wordCount: 2100, seoScore: 94, status: 'published' },
      { title: 'SEO Copywriting Masterclass', contentType: 'blog_post', targetKeyword: 'SEO copywriting', content: 'Advanced techniques for writing copy that ranks well and converts visitors into customers...', wordCount: 2700, seoScore: 91, status: 'draft' },
      { title: 'YouTube SEO Complete Guide', contentType: 'guide', targetKeyword: 'YouTube SEO', content: 'Optimize your YouTube videos for search to get more views and subscribers...', wordCount: 2300, seoScore: 88, status: 'published' },
      { title: 'International SEO Strategy', contentType: 'blog_post', targetKeyword: 'international SEO', content: 'How to implement international SEO for websites targeting multiple countries and languages...', wordCount: 2600, seoScore: 87, status: 'draft' },
    ];
    await ContentGeneration.bulkCreate(contents.map(c => ({ ...c, userId })));
    console.log('Seeded 15 content generation items.');

    // Seed Meta Tags (15 items)
    const metaTags = [
      { pageUrl: 'https://example.com/', metaTitle: 'Best SEO Tools & Software | Example.com', metaDescription: 'Discover the best SEO tools and software to boost your website rankings. Free and premium options compared.', ogTitle: 'Best SEO Tools & Software', ogDescription: 'Comprehensive comparison of top SEO tools', keywords: 'SEO tools, SEO software, best SEO tools', status: 'active' },
      { pageUrl: 'https://example.com/blog', metaTitle: 'SEO Blog - Tips, Guides & Strategies', metaDescription: 'Expert SEO blog with actionable tips, comprehensive guides, and proven strategies for better search rankings.', ogTitle: 'SEO Blog', ogDescription: 'Expert SEO tips and strategies', keywords: 'SEO blog, SEO tips, SEO strategies', status: 'active' },
      { pageUrl: 'https://example.com/services', metaTitle: 'Professional SEO Services | Get Found Online', metaDescription: 'Professional SEO services that drive results. Increase organic traffic, improve rankings, and grow your business.', ogTitle: 'Professional SEO Services', ogDescription: 'Expert SEO services for growth', keywords: 'SEO services, professional SEO, SEO agency', status: 'active' },
      { pageUrl: 'https://example.com/pricing', metaTitle: 'SEO Plans & Pricing | Affordable Packages', metaDescription: 'Transparent SEO pricing with packages for every budget. Start improving your search rankings today.', ogTitle: 'SEO Pricing Plans', ogDescription: 'Affordable SEO packages', keywords: 'SEO pricing, SEO plans, SEO packages', status: 'active' },
      { pageUrl: 'https://example.com/about', metaTitle: 'About Us - Leading SEO Experts Since 2018', metaDescription: 'Learn about our team of SEO experts with over 20 years of combined experience in search engine optimization.', ogTitle: 'About Our SEO Team', ogDescription: 'Meet our SEO experts', keywords: 'SEO experts, about us, SEO team', status: 'active' },
      { pageUrl: 'https://example.com/contact', metaTitle: 'Contact Us | Free SEO Consultation', metaDescription: 'Get in touch for a free SEO consultation. Our experts are ready to help you achieve your search goals.', ogTitle: 'Contact Us', ogDescription: 'Free SEO consultation', keywords: 'contact SEO, free consultation, SEO help', status: 'active' },
      { pageUrl: 'https://example.com/case-studies', metaTitle: 'SEO Case Studies | Proven Results', metaDescription: 'Real SEO case studies showing how we helped businesses increase organic traffic by up to 300%.', ogTitle: 'SEO Case Studies', ogDescription: 'Proven SEO results', keywords: 'SEO case studies, SEO results, success stories', status: 'active' },
      { pageUrl: 'https://example.com/tools/keyword-research', metaTitle: 'Free Keyword Research Tool | Find Profitable Keywords', metaDescription: 'Use our free keyword research tool to discover high-volume, low-competition keywords for your content strategy.', ogTitle: 'Free Keyword Research Tool', ogDescription: 'Find profitable keywords', keywords: 'keyword research, free tool, keyword finder', status: 'active' },
      { pageUrl: 'https://example.com/tools/site-audit', metaTitle: 'Free SEO Site Audit Tool | Check Your Website', metaDescription: 'Run a comprehensive SEO audit on your website. Identify issues and get actionable recommendations for improvement.', ogTitle: 'Free SEO Site Audit', ogDescription: 'Check your website SEO', keywords: 'site audit, SEO audit, website checker', status: 'active' },
      { pageUrl: 'https://example.com/tools/backlink-checker', metaTitle: 'Backlink Checker Tool | Analyze Your Link Profile', metaDescription: 'Check your backlink profile with our free tool. Discover linking domains, anchor texts, and link quality.', ogTitle: 'Backlink Checker Tool', ogDescription: 'Analyze your backlinks', keywords: 'backlink checker, link analysis, backlink tool', status: 'active' },
      { pageUrl: 'https://example.com/guides/beginners', metaTitle: 'SEO for Beginners | Complete Getting Started Guide', metaDescription: 'New to SEO? Our comprehensive beginner guide covers everything you need to know to start ranking higher.', ogTitle: 'SEO Beginners Guide', ogDescription: 'Learn SEO from scratch', keywords: 'SEO beginners, learn SEO, SEO guide', status: 'active' },
      { pageUrl: 'https://example.com/guides/advanced', metaTitle: 'Advanced SEO Techniques | Expert Strategies', metaDescription: 'Take your SEO to the next level with advanced techniques used by top-ranking websites.', ogTitle: 'Advanced SEO Guide', ogDescription: 'Expert SEO techniques', keywords: 'advanced SEO, expert SEO, SEO techniques', status: 'active' },
      { pageUrl: 'https://example.com/templates', metaTitle: 'Free SEO Templates | Content & Strategy Templates', metaDescription: 'Download free SEO templates for content planning, keyword research, site audits, and link building campaigns.', ogTitle: 'Free SEO Templates', ogDescription: 'Download SEO templates', keywords: 'SEO templates, content templates, free downloads', status: 'active' },
      { pageUrl: 'https://example.com/webinars', metaTitle: 'SEO Webinars | Learn From Industry Experts', metaDescription: 'Join our free SEO webinars featuring industry experts sharing the latest strategies and tactics.', ogTitle: 'SEO Webinars', ogDescription: 'Learn from SEO experts', keywords: 'SEO webinars, SEO training, learn SEO', status: 'active' },
      { pageUrl: 'https://example.com/newsletter', metaTitle: 'SEO Newsletter | Weekly Tips & Updates', metaDescription: 'Subscribe to our weekly SEO newsletter for the latest tips, algorithm updates, and industry insights.', ogTitle: 'SEO Newsletter', ogDescription: 'Weekly SEO updates', keywords: 'SEO newsletter, SEO updates, SEO tips', status: 'active' },
    ];
    await MetaTag.bulkCreate(metaTags.map(m => ({ ...m, userId })));
    console.log('Seeded 15 meta tag items.');

    // Seed SEO Audits (15 items)
    const audits = [
      { websiteUrl: 'https://techstartup.com', overallScore: 78, issuesFound: 12, recommendations: 'Fix broken links, optimize images, add structured data, improve mobile responsiveness', technicalScore: 82, contentScore: 75, status: 'completed' },
      { websiteUrl: 'https://ecommerce-shop.com', overallScore: 65, issuesFound: 23, recommendations: 'Improve page speed, fix duplicate content, add canonical tags, optimize product pages', technicalScore: 60, contentScore: 70, status: 'completed' },
      { websiteUrl: 'https://localbusiness.com', overallScore: 85, issuesFound: 8, recommendations: 'Enhance local schema markup, optimize Google My Business, build local citations', technicalScore: 88, contentScore: 82, status: 'completed' },
      { websiteUrl: 'https://blogplatform.io', overallScore: 72, issuesFound: 15, recommendations: 'Improve internal linking, fix thin content pages, optimize heading structure', technicalScore: 75, contentScore: 69, status: 'completed' },
      { websiteUrl: 'https://saasproduct.com', overallScore: 90, issuesFound: 5, recommendations: 'Minor image optimization needed, consider adding FAQ schema, improve CTA placement', technicalScore: 92, contentScore: 88, status: 'completed' },
      { websiteUrl: 'https://restaurant-chain.com', overallScore: 58, issuesFound: 28, recommendations: 'Major mobile issues, missing meta descriptions, poor page speed, no SSL on subpages', technicalScore: 52, contentScore: 64, status: 'completed' },
      { websiteUrl: 'https://healthclinic.org', overallScore: 81, issuesFound: 10, recommendations: 'Add medical schema markup, improve E-E-A-T signals, optimize for local search', technicalScore: 84, contentScore: 78, status: 'completed' },
      { websiteUrl: 'https://educationportal.edu', overallScore: 76, issuesFound: 14, recommendations: 'Fix crawl errors, optimize course pages, add breadcrumb navigation, improve site architecture', technicalScore: 79, contentScore: 73, status: 'completed' },
      { websiteUrl: 'https://news-outlet.com', overallScore: 88, issuesFound: 7, recommendations: 'Implement AMP pages, optimize article schema, improve Core Web Vitals', technicalScore: 90, contentScore: 86, status: 'completed' },
      { websiteUrl: 'https://fitness-brand.com', overallScore: 69, issuesFound: 19, recommendations: 'Fix JavaScript rendering issues, optimize images, add product schema, improve mobile UX', technicalScore: 65, contentScore: 73, status: 'completed' },
      { websiteUrl: 'https://travel-agency.com', overallScore: 74, issuesFound: 16, recommendations: 'Optimize for featured snippets, fix hreflang tags, improve page speed, add review schema', technicalScore: 71, contentScore: 77, status: 'completed' },
      { websiteUrl: 'https://lawfirm-partners.com', overallScore: 82, issuesFound: 9, recommendations: 'Enhance E-E-A-T signals, add attorney schema, optimize for local pack, improve content depth', technicalScore: 85, contentScore: 79, status: 'completed' },
      { websiteUrl: 'https://real-estate-co.com', overallScore: 71, issuesFound: 17, recommendations: 'Fix duplicate listings, add real estate schema, optimize property pages, improve site speed', technicalScore: 68, contentScore: 74, status: 'completed' },
      { websiteUrl: 'https://nonprofit-org.org', overallScore: 63, issuesFound: 22, recommendations: 'Major technical debt, outdated CMS, missing SSL pages, no structured data, poor mobile experience', technicalScore: 58, contentScore: 68, status: 'completed' },
      { websiteUrl: 'https://fintech-startup.io', overallScore: 87, issuesFound: 6, recommendations: 'Optimize for financial YMYL guidelines, add organization schema, improve trust signals', technicalScore: 89, contentScore: 85, status: 'completed' },
    ];
    await SEOAudit.bulkCreate(audits.map(a => ({ ...a, userId })));
    console.log('Seeded 15 SEO audit items.');

    // Seed Backlink Analysis (15 items)
    const backlinks = [
      { targetUrl: 'https://example.com', totalBacklinks: 4520, domainAuthority: 65, topReferrers: 'TechCrunch, Forbes, HubSpot, Moz, Search Engine Journal', anchorTexts: '["best SEO tool", "SEO software", "example.com", "click here"]', quality: 'high', status: 'analyzed' },
      { targetUrl: 'https://competitor1.com', totalBacklinks: 8900, domainAuthority: 78, topReferrers: 'CNN, NYT, Wikipedia, Reddit, Medium', anchorTexts: '["competitor brand", "SEO platform", "best software"]', quality: 'high', status: 'analyzed' },
      { targetUrl: 'https://myblog.com', totalBacklinks: 320, domainAuthority: 28, topReferrers: 'Guest posts, Blog comments, Forum links', anchorTexts: '["my blog", "read more", "article link"]', quality: 'medium', status: 'analyzed' },
      { targetUrl: 'https://startup-site.io', totalBacklinks: 1200, domainAuthority: 42, topReferrers: 'ProductHunt, Hacker News, Dev.to, GitHub', anchorTexts: '["startup tool", "new product", "innovative solution"]', quality: 'medium', status: 'analyzed' },
      { targetUrl: 'https://ecommerce-store.com', totalBacklinks: 5600, domainAuthority: 55, topReferrers: 'Shopping sites, Review blogs, Coupon sites', anchorTexts: '["shop now", "best deals", "product review"]', quality: 'medium', status: 'analyzed' },
      { targetUrl: 'https://agency-website.com', totalBacklinks: 2100, domainAuthority: 48, topReferrers: 'Clutch, DesignRush, GoodFirms, Agency directories', anchorTexts: '["top agency", "marketing agency", "SEO services"]', quality: 'high', status: 'analyzed' },
      { targetUrl: 'https://news-site.com', totalBacklinks: 15000, domainAuthority: 82, topReferrers: 'AP, Reuters, Yahoo News, Google News partners', anchorTexts: '["news source", "breaking news", "report"]', quality: 'high', status: 'analyzed' },
      { targetUrl: 'https://saas-platform.com', totalBacklinks: 3400, domainAuthority: 58, topReferrers: 'G2, Capterra, Software review sites', anchorTexts: '["software review", "SaaS tool", "platform review"]', quality: 'high', status: 'analyzed' },
      { targetUrl: 'https://local-shop.com', totalBacklinks: 180, domainAuthority: 18, topReferrers: 'Local directories, Yelp, Google Maps citations', anchorTexts: '["local store", "shop near me", "visit us"]', quality: 'low', status: 'analyzed' },
      { targetUrl: 'https://portfolio-site.dev', totalBacklinks: 95, domainAuthority: 15, topReferrers: 'GitHub, LinkedIn, Dribbble, Behance', anchorTexts: '["portfolio", "developer", "designer work"]', quality: 'low', status: 'analyzed' },
      { targetUrl: 'https://health-blog.com', totalBacklinks: 2800, domainAuthority: 51, topReferrers: 'WebMD, Healthline, Medical journals', anchorTexts: '["health tips", "medical advice", "wellness guide"]', quality: 'high', status: 'analyzed' },
      { targetUrl: 'https://finance-advisor.com', totalBacklinks: 1900, domainAuthority: 45, topReferrers: 'Investopedia, NerdWallet, Financial blogs', anchorTexts: '["financial advisor", "investment tips", "money guide"]', quality: 'medium', status: 'analyzed' },
      { targetUrl: 'https://edu-platform.com', totalBacklinks: 6200, domainAuthority: 68, topReferrers: 'University sites, Academic journals, Education portals', anchorTexts: '["learning platform", "online courses", "education"]', quality: 'high', status: 'analyzed' },
      { targetUrl: 'https://recipe-blog.com', totalBacklinks: 4100, domainAuthority: 52, topReferrers: 'Pinterest, Food Network, Recipe aggregators', anchorTexts: '["recipe", "cooking guide", "food blog"]', quality: 'medium', status: 'analyzed' },
      { targetUrl: 'https://tech-review.com', totalBacklinks: 7300, domainAuthority: 72, topReferrers: 'CNET, The Verge, TechRadar, Tom\'s Hardware', anchorTexts: '["tech review", "product comparison", "best picks"]', quality: 'high', status: 'analyzed' },
    ];
    await BacklinkAnalysis.bulkCreate(backlinks.map(b => ({ ...b, userId })));
    console.log('Seeded 15 backlink analysis items.');

    // Seed Content Optimizer (15 items)
    const optimizers = [
      { title: 'Homepage Content Optimization', originalContent: 'Welcome to our website. We offer great services.', optimizedContent: 'Discover industry-leading SEO services that drive measurable results. Our data-driven approach helps businesses achieve top rankings.', targetKeyword: 'SEO services', originalScore: 35, optimizedScore: 88, suggestions: 'Add more keywords, improve heading structure, add CTAs', status: 'optimized' },
      { title: 'Product Page: SEO Tool', originalContent: 'Our tool helps with SEO.', optimizedContent: 'Our AI-powered SEO tool analyzes your website and provides actionable insights to improve search rankings and drive organic traffic.', targetKeyword: 'SEO tool', originalScore: 28, optimizedScore: 91, suggestions: 'Expand features section, add testimonials, improve meta data', status: 'optimized' },
      { title: 'About Us Page Rewrite', originalContent: 'We are a company that does SEO.', optimizedContent: 'Founded in 2018, we are a team of certified SEO professionals dedicated to helping businesses achieve sustainable organic growth.', targetKeyword: 'SEO professionals', originalScore: 22, optimizedScore: 85, suggestions: 'Add team credentials, include E-E-A-T signals, add structured data', status: 'optimized' },
      { title: 'Blog Post: Link Building', originalContent: 'Link building is important for SEO.', optimizedContent: 'Link building remains one of the most critical ranking factors. Here are 10 proven strategies to earn high-quality backlinks in 2024.', targetKeyword: 'link building strategies', originalScore: 31, optimizedScore: 89, suggestions: 'Add statistics, include case studies, optimize images', status: 'optimized' },
      { title: 'Landing Page: Free Trial', originalContent: 'Try our product for free.', optimizedContent: 'Start your 14-day free trial and discover why 10,000+ marketers trust our SEO platform to drive organic growth.', targetKeyword: 'free SEO trial', originalScore: 25, optimizedScore: 92, suggestions: 'Add social proof, improve CTA visibility, add trust badges', status: 'optimized' },
      { title: 'Service Page: Content Marketing', originalContent: 'We do content marketing.', optimizedContent: 'Our strategic content marketing services help brands create compelling, SEO-optimized content that attracts, engages, and converts.', targetKeyword: 'content marketing services', originalScore: 20, optimizedScore: 87, suggestions: 'Add service details, include pricing, add FAQ section', status: 'optimized' },
      { title: 'Category Page: SEO Guides', originalContent: 'Browse our SEO guides.', optimizedContent: 'Explore our comprehensive library of SEO guides covering keyword research, technical SEO, link building, and content optimization.', targetKeyword: 'SEO guides', originalScore: 30, optimizedScore: 86, suggestions: 'Add subcategories, improve navigation, add featured guides', status: 'optimized' },
      { title: 'Blog Post: Core Web Vitals', originalContent: 'Core Web Vitals affect rankings.', optimizedContent: 'Core Web Vitals are Google confirmed ranking signals. Learn how to measure LCP, FID, and CLS, and optimize them for better rankings.', targetKeyword: 'core web vitals', originalScore: 33, optimizedScore: 90, suggestions: 'Add measurement tools, include benchmarks, add optimization steps', status: 'optimized' },
      { title: 'FAQ Page Optimization', originalContent: 'Here are some questions.', optimizedContent: 'Find answers to the most commonly asked SEO questions. From beginner concepts to advanced strategies, we cover everything.', targetKeyword: 'SEO FAQ', originalScore: 27, optimizedScore: 84, suggestions: 'Add FAQ schema, include related questions, improve answer depth', status: 'optimized' },
      { title: 'Pricing Page Revision', originalContent: 'See our prices below.', optimizedContent: 'Choose the perfect SEO plan for your business. All plans include keyword tracking, site audits, and dedicated support.', targetKeyword: 'SEO pricing', originalScore: 24, optimizedScore: 88, suggestions: 'Add comparison table, include testimonials, add money-back guarantee', status: 'optimized' },
      { title: 'Case Study Page', originalContent: 'Read about our success.', optimizedContent: 'Discover how we helped TechCorp increase organic traffic by 312% in 6 months through our data-driven SEO strategy.', targetKeyword: 'SEO case study', originalScore: 29, optimizedScore: 91, suggestions: 'Add metrics visualization, include timeline, add client quote', status: 'optimized' },
      { title: 'Blog Post: Local SEO', originalContent: 'Local SEO helps local businesses.', optimizedContent: 'Local SEO is essential for businesses serving specific geographic areas. Learn how to dominate the local pack and Google Maps results.', targetKeyword: 'local SEO tips', originalScore: 32, optimizedScore: 87, suggestions: 'Add local schema, include GMB tips, add citation sources', status: 'optimized' },
      { title: 'Newsletter Signup Page', originalContent: 'Sign up for our newsletter.', optimizedContent: 'Join 50,000+ SEO professionals getting weekly insights, algorithm updates, and actionable tips delivered straight to their inbox.', targetKeyword: 'SEO newsletter', originalScore: 21, optimizedScore: 85, suggestions: 'Add social proof numbers, include sample content, improve form design', status: 'optimized' },
      { title: 'Tool Comparison Article', originalContent: 'Compare SEO tools here.', optimizedContent: 'In-depth comparison of the top 10 SEO tools for 2024. Features, pricing, pros and cons analyzed to help you choose the right one.', targetKeyword: 'SEO tools comparison', originalScore: 34, optimizedScore: 93, suggestions: 'Add comparison table, include screenshots, add verdict section', status: 'optimized' },
      { title: 'Resource Hub Page', originalContent: 'Find resources here.', optimizedContent: 'Your one-stop SEO resource hub: free tools, templates, guides, webinars, and expert tutorials to master search engine optimization.', targetKeyword: 'SEO resources', originalScore: 26, optimizedScore: 86, suggestions: 'Categorize resources, add download counts, include difficulty levels', status: 'optimized' },
    ];
    await ContentOptimizer.bulkCreate(optimizers.map(o => ({ ...o, userId })));
    console.log('Seeded 15 content optimizer items.');

    // Seed SERP Analysis (15 items)
    const serps = [
      { keyword: 'best project management software', searchEngine: 'google', topResults: 'Monday.com, Asana, Trello dominate top 3. Mix of listicles and product pages.', featuredSnippet: true, avgWordCount: 2500, avgDomainAuthority: 75, status: 'analyzed' },
      { keyword: 'how to start a business', searchEngine: 'google', topResults: 'Forbes, NerdWallet, SBA.gov in top positions. Mostly guides and step-by-step articles.', featuredSnippet: true, avgWordCount: 3200, avgDomainAuthority: 85, status: 'analyzed' },
      { keyword: 'best CRM software 2024', searchEngine: 'google', topResults: 'PCMag, Forbes Advisor, G2 rankings dominate. Comparison articles perform best.', featuredSnippet: false, avgWordCount: 4000, avgDomainAuthority: 80, status: 'analyzed' },
      { keyword: 'digital marketing strategies', searchEngine: 'google', topResults: 'HubSpot, Neil Patel, WordStream rank highest. Educational content dominates.', featuredSnippet: true, avgWordCount: 2800, avgDomainAuthority: 78, status: 'analyzed' },
      { keyword: 'remote work tools', searchEngine: 'google', topResults: 'Zapier, TechRadar, Business News Daily. Listicle format preferred by Google.', featuredSnippet: false, avgWordCount: 2200, avgDomainAuthority: 72, status: 'analyzed' },
      { keyword: 'email marketing best practices', searchEngine: 'google', topResults: 'Mailchimp, HubSpot, Campaign Monitor. How-to guides rank well.', featuredSnippet: true, avgWordCount: 2600, avgDomainAuthority: 76, status: 'analyzed' },
      { keyword: 'website builder comparison', searchEngine: 'google', topResults: 'PCMag, TechRadar, Website Builder Expert. Detailed comparisons rank best.', featuredSnippet: false, avgWordCount: 3500, avgDomainAuthority: 74, status: 'analyzed' },
      { keyword: 'social media marketing tips', searchEngine: 'google', topResults: 'Sprout Social, Buffer, Hootsuite. Actionable tip-based articles perform well.', featuredSnippet: true, avgWordCount: 2100, avgDomainAuthority: 70, status: 'analyzed' },
      { keyword: 'cloud hosting providers', searchEngine: 'google', topResults: 'AWS, Azure, Google Cloud documentation plus comparison articles.', featuredSnippet: false, avgWordCount: 3000, avgDomainAuthority: 82, status: 'analyzed' },
      { keyword: 'data analytics tools', searchEngine: 'google', topResults: 'G2, Gartner, TrustRadius reviews dominate. Product comparison format wins.', featuredSnippet: true, avgWordCount: 2700, avgDomainAuthority: 77, status: 'analyzed' },
      { keyword: 'content management system comparison', searchEngine: 'google', topResults: 'WordPress.org, WPBeginner, PCMag. Guide-style content ranks highest.', featuredSnippet: true, avgWordCount: 3800, avgDomainAuthority: 79, status: 'analyzed' },
      { keyword: 'cybersecurity best practices', searchEngine: 'google', topResults: 'CISA, Norton, Kaspersky. Government and security company sites dominate.', featuredSnippet: true, avgWordCount: 2400, avgDomainAuthority: 83, status: 'analyzed' },
      { keyword: 'AI writing tools', searchEngine: 'google', topResults: 'Zapier, Elegant Themes, Authority Hacker. Listicles and reviews rank best.', featuredSnippet: false, avgWordCount: 3100, avgDomainAuthority: 71, status: 'analyzed' },
      { keyword: 'e-commerce platform comparison', searchEngine: 'google', topResults: 'Shopify, BigCommerce, Forbes Advisor. Comparison tables get featured snippets.', featuredSnippet: true, avgWordCount: 4200, avgDomainAuthority: 81, status: 'analyzed' },
      { keyword: 'SEO audit checklist', searchEngine: 'google', topResults: 'Ahrefs, Moz, SEMrush blog posts. Comprehensive checklists rank best.', featuredSnippet: true, avgWordCount: 3400, avgDomainAuthority: 80, status: 'analyzed' },
    ];
    await SERPAnalysis.bulkCreate(serps.map(s => ({ ...s, userId })));
    console.log('Seeded 15 SERP analysis items.');

    // Seed Competitor Analysis (15 items)
    const competitors = [
      { competitorUrl: 'https://ahrefs.com', competitorName: 'Ahrefs', organicKeywords: 485000, organicTraffic: 2800000, domainAuthority: 91, topPages: 'Blog, Tools, Academy', contentGaps: 'AI content generation, real-time SERP tracking', status: 'analyzed' },
      { competitorUrl: 'https://semrush.com', competitorName: 'SEMrush', organicKeywords: 520000, organicTraffic: 3200000, domainAuthority: 93, topPages: 'Blog, Tools, Courses', contentGaps: 'Local SEO focus, small business targeting', status: 'analyzed' },
      { competitorUrl: 'https://moz.com', competitorName: 'Moz', organicKeywords: 280000, organicTraffic: 1500000, domainAuthority: 91, topPages: 'Blog, Beginner Guide, Tools', contentGaps: 'Video content, interactive tools', status: 'analyzed' },
      { competitorUrl: 'https://neilpatel.com', competitorName: 'Neil Patel', organicKeywords: 350000, organicTraffic: 4100000, domainAuthority: 88, topPages: 'Blog, Ubersuggest, Guides', contentGaps: 'Enterprise solutions, API documentation', status: 'analyzed' },
      { competitorUrl: 'https://backlinko.com', competitorName: 'Backlinko', organicKeywords: 95000, organicTraffic: 780000, domainAuthority: 82, topPages: 'SEO guides, Case studies', contentGaps: 'Tool reviews, industry news', status: 'analyzed' },
      { competitorUrl: 'https://searchenginejournal.com', competitorName: 'Search Engine Journal', organicKeywords: 420000, organicTraffic: 3500000, domainAuthority: 90, topPages: 'News, Guides, Webinars', contentGaps: 'Hands-on tutorials, tool comparisons', status: 'analyzed' },
      { competitorUrl: 'https://hubspot.com', competitorName: 'HubSpot', organicKeywords: 680000, organicTraffic: 8900000, domainAuthority: 93, topPages: 'Blog, Templates, Tools', contentGaps: 'Deep technical SEO content', status: 'analyzed' },
      { competitorUrl: 'https://yoast.com', competitorName: 'Yoast', organicKeywords: 180000, organicTraffic: 1200000, domainAuthority: 85, topPages: 'Blog, Plugin, Academy', contentGaps: 'Non-WordPress content, advanced strategies', status: 'analyzed' },
      { competitorUrl: 'https://searchengineland.com', competitorName: 'Search Engine Land', organicKeywords: 310000, organicTraffic: 2100000, domainAuthority: 89, topPages: 'News, Guide, Library', contentGaps: 'Beginner content, tool recommendations', status: 'analyzed' },
      { competitorUrl: 'https://contentmarketinginstitute.com', competitorName: 'CMI', organicKeywords: 145000, organicTraffic: 890000, domainAuthority: 84, topPages: 'Blog, Research, Events', contentGaps: 'SEO-specific tools, technical guides', status: 'analyzed' },
      { competitorUrl: 'https://surfer.so', competitorName: 'Surfer SEO', organicKeywords: 65000, organicTraffic: 420000, domainAuthority: 72, topPages: 'Blog, Tool pages, Guides', contentGaps: 'Comprehensive SEO education', status: 'analyzed' },
      { competitorUrl: 'https://clearscope.io', competitorName: 'Clearscope', organicKeywords: 28000, organicTraffic: 180000, domainAuthority: 65, topPages: 'Blog, Product, Resources', contentGaps: 'Free tools, educational content', status: 'analyzed' },
      { competitorUrl: 'https://mangools.com', competitorName: 'Mangools', organicKeywords: 72000, organicTraffic: 510000, domainAuthority: 74, topPages: 'Blog, KWFinder, Tools', contentGaps: 'Advanced features, enterprise content', status: 'analyzed' },
      { competitorUrl: 'https://serpstat.com', competitorName: 'Serpstat', organicKeywords: 95000, organicTraffic: 620000, domainAuthority: 76, topPages: 'Blog, Tools, Academy', contentGaps: 'US market content, influencer content', status: 'analyzed' },
      { competitorUrl: 'https://majestic.com', competitorName: 'Majestic', organicKeywords: 48000, organicTraffic: 340000, domainAuthority: 80, topPages: 'Tools, Blog, Resources', contentGaps: 'Modern UI content, beginner guides', status: 'analyzed' },
    ];
    await CompetitorAnalysis.bulkCreate(competitors.map(c => ({ ...c, userId })));
    console.log('Seeded 15 competitor analysis items.');

    // Seed Title Generator (15 items)
    const titles = [
      { topic: 'SEO Basics', targetKeyword: 'SEO basics', generatedTitles: '1. SEO Basics: The Complete Beginner Guide\n2. Master SEO Basics in 30 Minutes\n3. 10 Essential SEO Basics Every Marketer Needs', selectedTitle: 'SEO Basics: The Complete Beginner Guide', clickThroughRate: 4.2, status: 'generated' },
      { topic: 'Content Marketing', targetKeyword: 'content marketing', generatedTitles: '1. Content Marketing Strategy: The Ultimate Guide\n2. 15 Content Marketing Tips That Drive Traffic\n3. How to Build a Content Marketing Machine', selectedTitle: 'Content Marketing Strategy: The Ultimate Guide', clickThroughRate: 3.8, status: 'generated' },
      { topic: 'Link Building', targetKeyword: 'link building', generatedTitles: '1. Link Building in 2024: What Actually Works\n2. 20 Link Building Strategies for Any Budget\n3. The Art of Link Building: A Practical Guide', selectedTitle: 'Link Building in 2024: What Actually Works', clickThroughRate: 5.1, status: 'generated' },
      { topic: 'Keyword Research', targetKeyword: 'keyword research', generatedTitles: '1. Keyword Research: Find Keywords That Convert\n2. How to Do Keyword Research Like a Pro\n3. The Ultimate Keyword Research Checklist', selectedTitle: 'Keyword Research: Find Keywords That Convert', clickThroughRate: 4.5, status: 'generated' },
      { topic: 'Technical SEO', targetKeyword: 'technical SEO', generatedTitles: '1. Technical SEO: The Complete Checklist\n2. Fix These 10 Technical SEO Issues Today\n3. Technical SEO Made Simple: A Visual Guide', selectedTitle: 'Technical SEO: The Complete Checklist', clickThroughRate: 3.9, status: 'generated' },
      { topic: 'Local SEO', targetKeyword: 'local SEO', generatedTitles: '1. Local SEO: Dominate Your Local Market\n2. 12 Local SEO Tips for Small Businesses\n3. The Local SEO Playbook for 2024', selectedTitle: 'Local SEO: Dominate Your Local Market', clickThroughRate: 4.7, status: 'generated' },
      { topic: 'E-commerce SEO', targetKeyword: 'ecommerce SEO', generatedTitles: '1. E-commerce SEO: Triple Your Store Traffic\n2. The Complete E-commerce SEO Guide\n3. 15 E-commerce SEO Mistakes Killing Sales', selectedTitle: 'E-commerce SEO: Triple Your Store Traffic', clickThroughRate: 5.3, status: 'generated' },
      { topic: 'Mobile SEO', targetKeyword: 'mobile SEO', generatedTitles: '1. Mobile SEO: Optimize for the Mobile-First Index\n2. 10 Mobile SEO Best Practices for 2024\n3. Is Your Site Mobile-Ready? A Complete Guide', selectedTitle: 'Mobile SEO: Optimize for the Mobile-First Index', clickThroughRate: 3.6, status: 'generated' },
      { topic: 'Voice Search', targetKeyword: 'voice search optimization', generatedTitles: '1. Voice Search Optimization: Prepare for the Future\n2. How to Optimize for Voice Search in 2024\n3. Voice Search SEO: The Complete Strategy Guide', selectedTitle: 'Voice Search Optimization: Prepare for the Future', clickThroughRate: 4.0, status: 'generated' },
      { topic: 'Video SEO', targetKeyword: 'video SEO', generatedTitles: '1. Video SEO: Rank Your Videos on Google & YouTube\n2. The Ultimate Video SEO Optimization Guide\n3. 10 Video SEO Tips to Get More Views', selectedTitle: 'Video SEO: Rank Your Videos on Google & YouTube', clickThroughRate: 4.8, status: 'generated' },
      { topic: 'Page Speed', targetKeyword: 'page speed optimization', generatedTitles: '1. Page Speed Optimization: The Definitive Guide\n2. How to Make Your Website Load in Under 2 Seconds\n3. 15 Page Speed Tweaks That Boost Rankings', selectedTitle: 'How to Make Your Website Load in Under 2 Seconds', clickThroughRate: 5.5, status: 'generated' },
      { topic: 'Schema Markup', targetKeyword: 'schema markup', generatedTitles: '1. Schema Markup Guide: Get Rich Snippets in Google\n2. How to Add Schema Markup to Your Website\n3. Schema Markup: The Secret to Standing Out in SERPs', selectedTitle: 'Schema Markup Guide: Get Rich Snippets in Google', clickThroughRate: 4.1, status: 'generated' },
      { topic: 'SEO Analytics', targetKeyword: 'SEO analytics', generatedTitles: '1. SEO Analytics: Track What Actually Matters\n2. The SEO Analytics Dashboard You Need\n3. How to Measure SEO Success: Key Metrics Guide', selectedTitle: 'SEO Analytics: Track What Actually Matters', clickThroughRate: 3.7, status: 'generated' },
      { topic: 'Content Strategy', targetKeyword: 'content strategy', generatedTitles: '1. Build a Content Strategy That Drives Revenue\n2. Content Strategy Framework: From Plan to Results\n3. 7 Steps to a Winning Content Strategy', selectedTitle: 'Build a Content Strategy That Drives Revenue', clickThroughRate: 4.4, status: 'generated' },
      { topic: 'SEO Tools', targetKeyword: 'best SEO tools', generatedTitles: '1. 25 Best SEO Tools (Free & Paid) for 2024\n2. SEO Tools Compared: Find Your Perfect Match\n3. The Only SEO Tools You Actually Need', selectedTitle: '25 Best SEO Tools (Free & Paid) for 2024', clickThroughRate: 5.0, status: 'generated' },
    ];
    await TitleGenerator.bulkCreate(titles.map(t => ({ ...t, userId })));
    console.log('Seeded 15 title generator items.');

    // Seed Blog Posts (15 items)
    const blogPosts = [
      { title: 'Complete Guide to On-Page SEO', topic: 'On-Page SEO', targetKeyword: 'on-page SEO guide', content: 'On-page SEO is the practice of optimizing individual web pages to rank higher in search engines. This comprehensive guide covers title tags, meta descriptions, heading structure, content optimization, internal linking, and image optimization.', excerpt: 'Master on-page SEO with this comprehensive guide...', wordCount: 2500, readingTime: 13, seoScore: 92, status: 'published' },
      { title: 'How to Build Quality Backlinks in 2024', topic: 'Link Building', targetKeyword: 'build quality backlinks', content: 'Building high-quality backlinks remains one of the most effective SEO strategies. Learn proven techniques including guest posting, broken link building, resource page outreach, and digital PR.', excerpt: 'Discover proven link building strategies...', wordCount: 3000, readingTime: 15, seoScore: 90, status: 'published' },
      { title: 'Keyword Research: A Step-by-Step Guide', topic: 'Keyword Research', targetKeyword: 'keyword research guide', content: 'Keyword research is the foundation of any successful SEO strategy. This step-by-step guide shows you how to find profitable keywords, analyze competition, and build a keyword strategy.', excerpt: 'Learn keyword research from scratch...', wordCount: 2200, readingTime: 11, seoScore: 88, status: 'published' },
      { title: 'Technical SEO Audit Checklist', topic: 'Technical SEO', targetKeyword: 'technical SEO audit', content: 'A comprehensive technical SEO audit checklist covering crawlability, indexation, site speed, mobile-friendliness, structured data, security, and international SEO considerations.', excerpt: 'The definitive technical SEO checklist...', wordCount: 3500, readingTime: 18, seoScore: 95, status: 'published' },
      { title: 'Content Marketing ROI: How to Measure', topic: 'Content Marketing', targetKeyword: 'content marketing ROI', content: 'Learn how to accurately measure the ROI of your content marketing efforts with practical metrics, attribution models, and reporting frameworks.', excerpt: 'Prove the value of content marketing...', wordCount: 1800, readingTime: 9, seoScore: 85, status: 'draft' },
      { title: 'Local SEO: The Complete Guide for Small Business', topic: 'Local SEO', targetKeyword: 'local SEO small business', content: 'Everything small businesses need to know about local SEO. From Google Business Profile optimization to local citations, reviews management, and local content strategy.', excerpt: 'Dominate local search results...', wordCount: 2800, readingTime: 14, seoScore: 91, status: 'published' },
      { title: 'E-commerce SEO Best Practices', topic: 'E-commerce SEO', targetKeyword: 'ecommerce SEO best practices', content: 'Optimize your online store for search engines with these proven e-commerce SEO best practices. Covers product pages, category pages, technical SEO, and content strategy for e-commerce.', excerpt: 'Boost your e-commerce organic traffic...', wordCount: 2600, readingTime: 13, seoScore: 89, status: 'published' },
      { title: 'Understanding Google Algorithm Updates', topic: 'Google Updates', targetKeyword: 'Google algorithm updates', content: 'A comprehensive overview of major Google algorithm updates and their impact on search rankings. Learn how to prepare for and adapt to algorithm changes.', excerpt: 'Stay ahead of Google algorithm changes...', wordCount: 2000, readingTime: 10, seoScore: 87, status: 'published' },
      { title: 'SEO vs PPC: Which Strategy is Right for You?', topic: 'SEO Strategy', targetKeyword: 'SEO vs PPC', content: 'A detailed comparison of SEO and PPC marketing strategies. Learn when to invest in organic search, when to use paid advertising, and how to combine both for maximum results.', excerpt: 'Compare SEO and PPC strategies...', wordCount: 1900, readingTime: 10, seoScore: 84, status: 'published' },
      { title: 'The Ultimate Guide to Schema Markup', topic: 'Schema Markup', targetKeyword: 'schema markup guide', content: 'Learn how to implement schema markup on your website to get rich snippets in Google. Covers Article, Product, FAQ, How-to, and Organization schema types.', excerpt: 'Get rich snippets with schema markup...', wordCount: 2400, readingTime: 12, seoScore: 90, status: 'draft' },
      { title: 'How to Write SEO-Friendly Blog Posts', topic: 'SEO Writing', targetKeyword: 'SEO-friendly blog posts', content: 'Master the art of writing blog posts that rank well in search engines while keeping readers engaged. Covers keyword placement, readability, formatting, and content structure.', excerpt: 'Write blog posts that rank and convert...', wordCount: 2100, readingTime: 11, seoScore: 86, status: 'published' },
      { title: 'Core Web Vitals: Everything You Need to Know', topic: 'Core Web Vitals', targetKeyword: 'core web vitals guide', content: 'A comprehensive guide to Google Core Web Vitals metrics: LCP, FID/INP, and CLS. Learn how to measure, diagnose, and fix issues to improve your page experience scores.', excerpt: 'Optimize your Core Web Vitals scores...', wordCount: 2700, readingTime: 14, seoScore: 93, status: 'published' },
      { title: 'International SEO: Targeting Global Markets', topic: 'International SEO', targetKeyword: 'international SEO guide', content: 'Guide to implementing international SEO for websites targeting multiple countries. Covers hreflang tags, URL structure, content localization, and market-specific strategies.', excerpt: 'Expand your SEO globally...', wordCount: 2300, readingTime: 12, seoScore: 88, status: 'draft' },
      { title: 'Image SEO: A Complete Optimization Guide', topic: 'Image SEO', targetKeyword: 'image SEO optimization', content: 'Optimize your images for search engines with proper alt text, file naming, compression, lazy loading, and next-gen formats. Includes tips for Google Images ranking.', excerpt: 'Boost traffic with image optimization...', wordCount: 1700, readingTime: 9, seoScore: 83, status: 'published' },
      { title: 'SEO Reporting: Metrics That Matter', topic: 'SEO Analytics', targetKeyword: 'SEO reporting metrics', content: 'Create impactful SEO reports that demonstrate value. Learn which metrics to track, how to visualize data, and how to present SEO progress to stakeholders.', excerpt: 'Track and report SEO success...', wordCount: 2000, readingTime: 10, seoScore: 85, status: 'published' },
    ];
    await BlogPost.bulkCreate(blogPosts.map(b => ({ ...b, userId })));
    console.log('Seeded 15 blog post items.');

    // Seed Product Descriptions (15 items)
    const products = [
      { productName: 'SEO Pro Toolkit', category: 'Software', features: 'Keyword research, site audit, rank tracking, backlink analysis', description: 'All-in-one SEO toolkit for professionals. Includes 50+ features for comprehensive website optimization.', seoDescription: 'Professional SEO toolkit with keyword research, site audits, and rank tracking.', targetAudience: 'SEO professionals', tone: 'professional', status: 'active' },
      { productName: 'Content Writer AI', category: 'Software', features: 'AI writing, SEO optimization, plagiarism check, readability analysis', description: 'AI-powered content writing tool that generates SEO-optimized articles, blog posts, and marketing copy.', seoDescription: 'AI content writer that creates SEO-optimized content automatically.', targetAudience: 'Content marketers', tone: 'professional', status: 'active' },
      { productName: 'Keyword Explorer', category: 'Tool', features: 'Search volume, keyword difficulty, CPC data, SERP analysis', description: 'Advanced keyword research tool with accurate search volume data and competition metrics.', seoDescription: 'Find profitable keywords with accurate search volume and difficulty data.', targetAudience: 'Digital marketers', tone: 'professional', status: 'active' },
      { productName: 'Backlink Monitor', category: 'Software', features: 'Link tracking, toxic link detection, competitor backlinks, alerts', description: 'Monitor your backlink profile in real-time. Get alerts for new and lost links, detect toxic backlinks.', seoDescription: 'Real-time backlink monitoring with toxic link detection and alerts.', targetAudience: 'SEO specialists', tone: 'professional', status: 'active' },
      { productName: 'Rank Tracker Pro', category: 'Tool', features: 'Daily ranking updates, local tracking, competitor comparison, reports', description: 'Track your keyword rankings daily across multiple search engines and locations.', seoDescription: 'Daily keyword rank tracking across search engines with competitor comparison.', targetAudience: 'SEO agencies', tone: 'professional', status: 'active' },
      { productName: 'Site Speed Optimizer', category: 'Tool', features: 'Image compression, code minification, caching, CDN integration', description: 'Automatically optimize your website speed with one-click improvements for images, code, and caching.', seoDescription: 'Optimize website speed with automatic image compression and code minification.', targetAudience: 'Web developers', tone: 'technical', status: 'active' },
      { productName: 'Schema Generator Pro', category: 'Tool', features: 'JSON-LD generator, validation, rich snippet preview, bulk generation', description: 'Generate valid Schema.org markup for any page type. Supports Article, Product, FAQ, and 30+ schema types.', seoDescription: 'Generate valid Schema.org JSON-LD markup for rich snippets in Google.', targetAudience: 'Webmasters', tone: 'technical', status: 'active' },
      { productName: 'Social SEO Suite', category: 'Software', features: 'Social signals tracking, OG tag optimization, social sharing analysis', description: 'Bridge the gap between social media and SEO. Optimize social sharing and track social signals impact.', seoDescription: 'Optimize social media for SEO with social signals tracking and OG tag management.', targetAudience: 'Social media managers', tone: 'casual', status: 'active' },
      { productName: 'Local SEO Manager', category: 'Software', features: 'GMB management, citation building, review monitoring, local rank tracking', description: 'Complete local SEO management platform. Manage Google Business Profile, citations, and reviews from one dashboard.', seoDescription: 'Manage local SEO with GMB optimization, citation building, and review monitoring.', targetAudience: 'Local businesses', tone: 'friendly', status: 'active' },
      { productName: 'Content Calendar Pro', category: 'Tool', features: 'Editorial calendar, workflow management, team collaboration, publishing', description: 'Plan, create, and publish SEO content with an intuitive editorial calendar and team collaboration features.', seoDescription: 'SEO content calendar with team collaboration and workflow management.', targetAudience: 'Content teams', tone: 'professional', status: 'active' },
      { productName: 'SEO Audit Dashboard', category: 'Software', features: 'Automated audits, issue tracking, priority scoring, fix suggestions', description: 'Automated SEO auditing tool that crawls your site, identifies issues, and provides prioritized fix recommendations.', seoDescription: 'Automated SEO site audits with prioritized recommendations and fix tracking.', targetAudience: 'SEO managers', tone: 'professional', status: 'active' },
      { productName: 'Competitor Spy Tool', category: 'Tool', features: 'Traffic estimation, keyword gap analysis, content comparison, alerts', description: 'Monitor your competitors SEO strategies. Track their rankings, content, and backlinks to find opportunities.', seoDescription: 'Spy on competitor SEO strategies with traffic estimation and keyword gap analysis.', targetAudience: 'Marketing teams', tone: 'professional', status: 'active' },
      { productName: 'Meta Tag Optimizer', category: 'Tool', features: 'SERP preview, character counter, A/B testing, bulk editing', description: 'Optimize your meta titles and descriptions with SERP previews, A/B testing, and bulk editing capabilities.', seoDescription: 'Optimize meta tags with SERP preview, A/B testing, and bulk editing tools.', targetAudience: 'SEO specialists', tone: 'professional', status: 'active' },
      { productName: 'Link Building Outreach', category: 'Software', features: 'Prospect finder, email templates, follow-up automation, tracking', description: 'Streamline your link building outreach with automated prospect finding, personalized templates, and follow-up tracking.', seoDescription: 'Automated link building outreach with prospect finding and email templates.', targetAudience: 'Link builders', tone: 'professional', status: 'active' },
      { productName: 'SEO Report Generator', category: 'Tool', features: 'White-label reports, automated delivery, custom branding, data visualization', description: 'Create professional, white-label SEO reports automatically. Customizable templates with beautiful data visualizations.', seoDescription: 'Generate white-label SEO reports with automated delivery and custom branding.', targetAudience: 'SEO agencies', tone: 'professional', status: 'active' },
    ];
    await ProductDescription.bulkCreate(products.map(p => ({ ...p, userId })));
    console.log('Seeded 15 product description items.');

    // Seed FAQ Generator (15 items)
    const faqs = [
      { topic: 'SEO Basics', targetKeyword: 'SEO basics FAQ', questions: 'What is SEO? How long does SEO take? What is keyword research? How do backlinks work? What is on-page SEO?', answers: 'SEO stands for Search Engine Optimization. It typically takes 3-6 months. Keyword research finds search terms. Backlinks are links from other sites. On-page SEO optimizes individual pages.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'Content Marketing', targetKeyword: 'content marketing FAQ', questions: 'What is content marketing? How to create a content strategy? What types of content work best? How to measure content ROI?', answers: 'Content marketing creates valuable content. Strategy starts with audience research. Blog posts, videos, and infographics work well. Track conversions and organic traffic.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'Technical SEO', targetKeyword: 'technical SEO FAQ', questions: 'What is technical SEO? How to improve site speed? What is crawlability? How to fix indexing issues? What are Core Web Vitals?', answers: 'Technical SEO optimizes site infrastructure. Use compression, caching, CDN. Crawlability is search engine access. Use Search Console for indexing. CWV measure page experience.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'Link Building', targetKeyword: 'link building FAQ', questions: 'What is link building? Are all backlinks equal? How many backlinks do I need? What is anchor text? Is link buying safe?', answers: 'Link building earns external links. No, quality matters most. Focus on quality over quantity. Anchor text is clickable link text. Buying links violates Google guidelines.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'Local SEO', targetKeyword: 'local SEO FAQ', questions: 'What is local SEO? How to optimize Google Business Profile? What are local citations? How important are reviews?', answers: 'Local SEO targets geographic searches. Complete all GMB fields. Citations are business listings. Reviews significantly impact local rankings.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'E-commerce SEO', targetKeyword: 'ecommerce SEO FAQ', questions: 'How to optimize product pages? What about duplicate content? How to handle out-of-stock pages? Category page SEO tips?', answers: 'Unique descriptions, schema markup. Use canonical tags. Keep pages with 301 redirect. Optimize category text and filters.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'Mobile SEO', targetKeyword: 'mobile SEO FAQ', questions: 'What is mobile-first indexing? How to make a site mobile-friendly? Does page speed matter on mobile? What about AMP?', answers: 'Google primarily uses mobile version. Use responsive design. Speed is critical on mobile. AMP is optional but helps speed.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'Keyword Research', targetKeyword: 'keyword research FAQ', questions: 'How to find keywords? What is keyword difficulty? How to choose keywords? What is search intent? Best keyword tools?', answers: 'Use research tools and competitor analysis. KD measures ranking difficulty. Balance volume and competition. Intent is the why behind searches. Ahrefs, SEMrush, Google Keyword Planner.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'SEO Tools', targetKeyword: 'SEO tools FAQ', questions: 'What SEO tools do I need? Free vs paid tools? Best all-in-one SEO tool? Do I need multiple tools?', answers: 'At minimum: Search Console, Analytics. Paid tools offer more data. SEMrush and Ahrefs lead. Most agencies use 2-3 tools.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'Google Analytics', targetKeyword: 'Google Analytics FAQ', questions: 'How to set up GA4? What metrics matter for SEO? How to track conversions? GA4 vs Universal Analytics?', answers: 'Install tag via GTM or code. Organic traffic, bounce rate, time on page. Set up goals and events. GA4 is event-based, more powerful.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'Schema Markup', targetKeyword: 'schema markup FAQ', questions: 'What is schema markup? How to implement it? Does it help rankings? What types of schema are there?', answers: 'Structured data for search engines. Add JSON-LD to page HTML. Indirectly through rich results. Article, Product, FAQ, HowTo, and many more.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'International SEO', targetKeyword: 'international SEO FAQ', questions: 'What are hreflang tags? ccTLD vs subdomain? How to localize content? Should I translate or create new content?', answers: 'Hreflang tells Google language/region. ccTLD for dedicated markets. Adapt to local culture. Ideally create unique local content.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'SEO Penalties', targetKeyword: 'SEO penalties FAQ', questions: 'What is a Google penalty? How to check for penalties? How to recover? What causes penalties?', answers: 'Manual or algorithmic ranking drops. Check Search Console manual actions. Disavow bad links, fix issues. Link schemes, thin content, cloaking.', faqCount: 10, schemaGenerated: true, status: 'generated' },
      { topic: 'Voice Search SEO', targetKeyword: 'voice search FAQ', questions: 'How does voice search affect SEO? How to optimize for voice? What is conversational search?', answers: 'More conversational queries. Use natural language, answer questions directly. Long-tail, question-based searches.', faqCount: 8, schemaGenerated: true, status: 'generated' },
      { topic: 'SEO Strategy', targetKeyword: 'SEO strategy FAQ', questions: 'How to create an SEO strategy? How often to update strategy? What KPIs to track? SEO budget recommendations?', answers: 'Start with audit, set goals, plan content. Review quarterly. Organic traffic, rankings, conversions. 5-10% of marketing budget minimum.', faqCount: 10, schemaGenerated: true, status: 'generated' },
    ];
    await FAQGenerator.bulkCreate(faqs.map(f => ({ ...f, userId })));
    console.log('Seeded 15 FAQ generator items.');

    // Seed Schema Markup (15 items)
    const schemas = [
      { pageUrl: 'https://example.com/blog/seo-guide', schemaType: 'Article', schemaData: '{"@type":"Article","headline":"Complete SEO Guide","author":"John Doe","datePublished":"2024-01-15"}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/products/seo-tool', schemaType: 'Product', schemaData: '{"@type":"Product","name":"SEO Pro Tool","price":"49.99","currency":"USD","rating":"4.8"}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/faq', schemaType: 'FAQPage', schemaData: '{"@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What is SEO?"}]}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/how-to/keyword-research', schemaType: 'HowTo', schemaData: '{"@type":"HowTo","name":"How to Do Keyword Research","step":[{"@type":"HowToStep"}]}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/about', schemaType: 'Organization', schemaData: '{"@type":"Organization","name":"SEO Content AI","url":"https://example.com","logo":"..."}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/contact', schemaType: 'LocalBusiness', schemaData: '{"@type":"LocalBusiness","name":"SEO Agency","address":{"@type":"PostalAddress"}}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/blog/seo-tips', schemaType: 'BlogPosting', schemaData: '{"@type":"BlogPosting","headline":"10 SEO Tips","author":"Jane Smith","wordCount":2500}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/reviews', schemaType: 'Review', schemaData: '{"@type":"Review","itemReviewed":{"@type":"SoftwareApplication"},"reviewRating":{"ratingValue":"5"}}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/events/webinar', schemaType: 'Event', schemaData: '{"@type":"Event","name":"SEO Webinar 2024","startDate":"2024-06-15","location":{"@type":"VirtualLocation"}}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/courses/seo', schemaType: 'Course', schemaData: '{"@type":"Course","name":"SEO Masterclass","provider":{"@type":"Organization","name":"SEO Academy"}}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/', schemaType: 'WebSite', schemaData: '{"@type":"WebSite","name":"SEO Content AI","url":"https://example.com","potentialAction":{"@type":"SearchAction"}}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/team', schemaType: 'Person', schemaData: '{"@type":"Person","name":"John Doe","jobTitle":"SEO Director","worksFor":"SEO Content AI"}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/videos/seo-tutorial', schemaType: 'VideoObject', schemaData: '{"@type":"VideoObject","name":"SEO Tutorial","description":"Learn SEO basics","duration":"PT15M"}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/breadcrumb-test', schemaType: 'BreadcrumbList', schemaData: '{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home"}]}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
      { pageUrl: 'https://example.com/recipes/seo-success', schemaType: 'Article', schemaData: '{"@type":"Article","headline":"Recipe for SEO Success","author":"SEO Team","datePublished":"2024-03-01"}', validationStatus: 'valid', implementationCode: '<script type="application/ld+json">...</script>', status: 'generated' },
    ];
    await SchemaMarkup.bulkCreate(schemas.map(s => ({ ...s, userId })));
    console.log('Seeded 15 schema markup items.');

    // Seed Content Calendar (15 items)
    const calendar = [
      { title: 'SEO Trends 2024 Blog Post', contentType: 'blog_post', targetKeyword: 'SEO trends 2024', scheduledDate: new Date('2024-03-18'), assignee: 'John Doe', priority: 'high', notes: 'Cover AI impact, Core Web Vitals updates, and E-E-A-T changes', status: 'planned' },
      { title: 'Keyword Research Video Tutorial', contentType: 'video', targetKeyword: 'keyword research tutorial', scheduledDate: new Date('2024-03-20'), assignee: 'Jane Smith', priority: 'high', notes: 'Screen recording with Ahrefs walkthrough', status: 'in_progress' },
      { title: 'Link Building Infographic', contentType: 'infographic', targetKeyword: 'link building strategies', scheduledDate: new Date('2024-03-22'), assignee: 'Design Team', priority: 'medium', notes: 'Visual guide to 10 link building methods', status: 'planned' },
      { title: 'Monthly SEO Newsletter', contentType: 'newsletter', targetKeyword: 'SEO updates', scheduledDate: new Date('2024-03-25'), assignee: 'Marketing Team', priority: 'high', notes: 'Include algorithm updates, case study highlight, and tool recommendations', status: 'planned' },
      { title: 'E-commerce SEO Case Study', contentType: 'case_study', targetKeyword: 'ecommerce SEO case study', scheduledDate: new Date('2024-03-28'), assignee: 'Sarah Johnson', priority: 'medium', notes: 'Document TechStore.com traffic growth from 10K to 50K monthly', status: 'planned' },
      { title: 'Technical SEO Webinar', contentType: 'webinar', targetKeyword: 'technical SEO training', scheduledDate: new Date('2024-04-01'), assignee: 'John Doe', priority: 'high', notes: 'Live demo of site audit process, Q&A session', status: 'planned' },
      { title: 'Local SEO Guide Update', contentType: 'blog_post', targetKeyword: 'local SEO guide', scheduledDate: new Date('2024-04-03'), assignee: 'Mike Brown', priority: 'medium', notes: 'Update with new Google Business Profile features', status: 'planned' },
      { title: 'SEO Tool Comparison Post', contentType: 'blog_post', targetKeyword: 'best SEO tools comparison', scheduledDate: new Date('2024-04-05'), assignee: 'Jane Smith', priority: 'high', notes: 'Compare top 10 SEO tools with pricing and features', status: 'planned' },
      { title: 'Social Media for SEO Podcast', contentType: 'podcast', targetKeyword: 'social media SEO', scheduledDate: new Date('2024-04-08'), assignee: 'Content Team', priority: 'low', notes: 'Interview with social media SEO expert', status: 'planned' },
      { title: 'Schema Markup Tutorial Series', contentType: 'tutorial', targetKeyword: 'schema markup tutorial', scheduledDate: new Date('2024-04-10'), assignee: 'Dev Team', priority: 'medium', notes: '5-part series covering different schema types', status: 'planned' },
      { title: 'SEO Audit Template Download', contentType: 'template', targetKeyword: 'SEO audit template', scheduledDate: new Date('2024-04-12'), assignee: 'Sarah Johnson', priority: 'medium', notes: 'Downloadable spreadsheet with 200+ audit items', status: 'planned' },
      { title: 'Core Web Vitals Deep Dive', contentType: 'blog_post', targetKeyword: 'core web vitals optimization', scheduledDate: new Date('2024-04-15'), assignee: 'John Doe', priority: 'high', notes: 'Detailed technical guide with real examples', status: 'planned' },
      { title: 'AI and SEO White Paper', contentType: 'white_paper', targetKeyword: 'AI SEO impact', scheduledDate: new Date('2024-04-18'), assignee: 'Research Team', priority: 'high', notes: 'Research-backed analysis of AI impact on SEO industry', status: 'planned' },
      { title: 'Competitor Analysis Workshop', contentType: 'workshop', targetKeyword: 'competitor SEO analysis', scheduledDate: new Date('2024-04-22'), assignee: 'Marketing Team', priority: 'medium', notes: 'Interactive workshop with live competitor analysis', status: 'planned' },
      { title: 'Monthly SEO Performance Report', contentType: 'report', targetKeyword: 'SEO reporting', scheduledDate: new Date('2024-04-25'), assignee: 'Analytics Team', priority: 'high', notes: 'Monthly client report template with KPIs and insights', status: 'planned' },
    ];
    await ContentCalendar.bulkCreate(calendar.map(c => ({ ...c, userId })));
    console.log('Seeded 15 content calendar items.');

    // Seed Readability Analysis (15 items)
    const readability = [
      { title: 'Homepage Copy Analysis', content: 'Welcome to the premier SEO platform...', fleschScore: 65.2, gradeLevel: '8th Grade', avgSentenceLength: 16.5, passiveVoicePercent: 12.0, suggestions: 'Shorten sentences, use more active voice, simplify vocabulary', status: 'analyzed' },
      { title: 'Product Page Copy', content: 'Our revolutionary SEO tool transforms...', fleschScore: 58.4, gradeLevel: '10th Grade', avgSentenceLength: 19.2, passiveVoicePercent: 18.5, suggestions: 'Too complex for general audience, simplify technical jargon', status: 'analyzed' },
      { title: 'Blog Post: SEO Tips', content: 'Here are 10 simple SEO tips...', fleschScore: 72.8, gradeLevel: '7th Grade', avgSentenceLength: 14.3, passiveVoicePercent: 8.0, suggestions: 'Good readability, consider adding more transition words', status: 'analyzed' },
      { title: 'Technical Documentation', content: 'The API endpoint accepts...', fleschScore: 42.1, gradeLevel: '12th Grade', avgSentenceLength: 22.8, passiveVoicePercent: 25.0, suggestions: 'Highly technical, appropriate for developer audience', status: 'analyzed' },
      { title: 'Email Newsletter Copy', content: 'This week in SEO news...', fleschScore: 78.5, gradeLevel: '6th Grade', avgSentenceLength: 12.1, passiveVoicePercent: 5.0, suggestions: 'Excellent readability, engaging and accessible', status: 'analyzed' },
      { title: 'Case Study Write-up', content: 'Our client experienced remarkable growth...', fleschScore: 55.3, gradeLevel: '10th Grade', avgSentenceLength: 20.5, passiveVoicePercent: 22.0, suggestions: 'Reduce passive voice, break up long paragraphs, add subheadings', status: 'analyzed' },
      { title: 'Landing Page Copy', content: 'Transform your SEO results today...', fleschScore: 70.1, gradeLevel: '7th Grade', avgSentenceLength: 13.7, passiveVoicePercent: 7.0, suggestions: 'Good for conversions, consider adding more power words', status: 'analyzed' },
      { title: 'Help Center Article', content: 'To get started with our platform...', fleschScore: 75.6, gradeLevel: '6th Grade', avgSentenceLength: 11.8, passiveVoicePercent: 6.0, suggestions: 'Clear and concise, add more step-by-step formatting', status: 'analyzed' },
      { title: 'Press Release', content: 'SEO Content AI announces the launch...', fleschScore: 48.9, gradeLevel: '11th Grade', avgSentenceLength: 21.3, passiveVoicePercent: 28.0, suggestions: 'Too formal, reduce jargon for broader distribution', status: 'analyzed' },
      { title: 'Social Media Post Copy', content: 'Boost your rankings with these tips...', fleschScore: 82.3, gradeLevel: '5th Grade', avgSentenceLength: 9.5, passiveVoicePercent: 3.0, suggestions: 'Perfect for social media, punchy and engaging', status: 'analyzed' },
      { title: 'Whitepaper Introduction', content: 'The landscape of search engine optimization...', fleschScore: 38.7, gradeLevel: '12th Grade+', avgSentenceLength: 24.6, passiveVoicePercent: 30.0, suggestions: 'Very academic, appropriate for industry professionals only', status: 'analyzed' },
      { title: 'Tutorial: Setting Up Analytics', content: 'Follow these steps to set up...', fleschScore: 71.4, gradeLevel: '7th Grade', avgSentenceLength: 15.0, passiveVoicePercent: 10.0, suggestions: 'Good instructional writing, add more visual aids references', status: 'analyzed' },
      { title: 'Comparison Article', content: 'When choosing an SEO tool...', fleschScore: 63.8, gradeLevel: '9th Grade', avgSentenceLength: 17.8, passiveVoicePercent: 14.0, suggestions: 'Add more comparison tables, reduce subjective language', status: 'analyzed' },
      { title: 'FAQ Page Content', content: 'Frequently asked questions about SEO...', fleschScore: 74.2, gradeLevel: '7th Grade', avgSentenceLength: 13.2, passiveVoicePercent: 9.0, suggestions: 'Good Q&A format, ensure answers are comprehensive but concise', status: 'analyzed' },
      { title: 'Onboarding Email Series', content: 'Welcome to SEO Content AI...', fleschScore: 76.9, gradeLevel: '6th Grade', avgSentenceLength: 12.5, passiveVoicePercent: 6.0, suggestions: 'Excellent onboarding copy, friendly and actionable', status: 'analyzed' },
    ];
    await ReadabilityAnalysis.bulkCreate(readability.map(r => ({ ...r, userId })));
    console.log('Seeded 15 readability analysis items.');

    console.log('\n✅ Database seeded successfully!');
    console.log('Login credentials: demo@seocontent.ai / password123');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
